[package]
name = "stutter"
version = "0.1.0"
authors = ["Kyle Kloberdanz <kyle.g.kloberdanz@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0"
rpds = "0.6.0"
num-bigint = "0.2"
num-traits = "0.2"
