[package]
name = "stutter"
version = "0.1.0"
authors = ["Kyle Kloberdanz <kyle.g.kloberdanz@gmail.com>"]
edition = "2018"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
rpds = "0.11"
structopt = "0.3.26"

[profile.release]
opt-level = 3
overflow-checks = false
lto = "fat"
